version: "3.7"
services:
    api:
        container_name: apilistgw
        build:
            context: ./
            target: apilistgw
        ports:
            - 3317:3317
        volumes:
            - ../APIGateway/config/krakend/:public/unified
        restart: always
